### ISSUE TITLE
Password is stored as a PLAIN TEXT

### ISSUE THREAD

**Issue by Dancho80** [janjoerke/vscode-jenkins-pipeline-linter-connector#5]
Seems like the password is not encrypted and cannot be used that way
![image](https://user-images.githubusercontent.com/17573785/49369676-ad076500-f6fa-11e8-841f-8a51de9d0651.png)

**Comment by janjoerke** [comment]
Yes, that is indeed bad. 

The problem is, that VS Code does not offer an API for securely storing passwords. Implementing a custom credential store is sadly far above the time i can spend on the plugin at the moment.

For now i will add the possibility to leave the password field empty, so that when a user is set and a password is not, you than can enter your password manually.

**Comment by janjoerke** [comment]
I've implemented the change in 1.1.4.
